# Generated by Django 4.2.1 on 2023-05-16 07:30

import Rooms.functions.upload_location
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('Standard', 'STANDARD'), ('Double Room', 'DOUBLE'), ('Suite', 'SUITE'), ('Executive', 'EXECUTIVE'), ('Deluxe', 'DELUXE'), ('Villa', 'VILLA')], default='Standard', max_length=50)),
                ('availability', models.CharField(choices=[('Booked', 'BOOKED'), ('Available', 'AVAILABLE')], default='Available', max_length=50)),
                ('price', models.FloatField()),
                ('room_image', models.FileField(upload_to=Rooms.functions.upload_location.UploadLocation.room_location)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Rooms',
            },
        ),
    ]
