# Generated by Django 4.2.1 on 2023-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Room'},
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
